# -*- coding: utf-8 -*-
"""Sql queries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtxWlHxSDeLT2b0OkUVlz4px-TAFMcdC
"""

#this is creatation of sql queries to make tables
CREATE TABLE Orders (
  OrderID int,
  CustomerID int,
  OrderDate datetime,
  OrderTime varchar(8),
  PRIMARY KEY (OrderID)
);

CREATE TABLE OrderDetails (
  OrderDetailID int,
  OrderID int,
  ProductID int,
  Quantity int,
  PRIMARY KEY (OrderDetailID)
);

CREATE TABLE Products (
  ProductID int,
  ProductName varchar(50),
  Category varchar(50),
  UnitPrice decimal(10, 2),
  Stock int,
  PRIMARY KEY (ProductID)
);

CREATE TABLE Customers (
  CustomerID int,
  FirstName varchar(50),
  LastName varchar(50),
  Email varchar(100),
  Phone varchar(20),
  PRIMARY KEY (CustomerID)
);

!pip install openai

from openai import OpenAI
client = OpenAI()

response = client.chat.completions.create(
  model="gpt-3.5-turbo-16k",
  messages=[
    {
      "role": "system",
      "content": "Given the following SQL tables, your job is to write queries given a user’s request.\n
       \n    CREATE TABLE Orders (\n      OrderID int,\n      CustomerID int,\n      OrderDate datetime,\n
                                  OrderTime varchar(8),\n      PRIMARY KEY (OrderID)\n    );\n    \n
       CREATE TABLE OrderDetails (\n      OrderDetailID int,\n      OrderID int,\n      ProductID int,\n
                                  Quantity int,\n      PRIMARY KEY (OrderDetailID)\n    );\n    \n
       CREATE TABLE Products (\n      ProductID int,\n      ProductName varchar(50),\n
                              Category varchar(50),\n      UnitPrice decimal(10, 2),\n
                              Stock int,\n      PRIMARY KEY (ProductID)\n    );\n    \n
        CREATE TABLE Customers (\n      CustomerID int,\n      FirstName varchar(50),\n
                                LastName varchar(50),\n      Email varchar(100),\n
                                Phone varchar(20),\n      PRIMARY KEY (CustomerID)\n    );"
    },
    {
      "role": "user",
      "content": "Write a SQL query which computes the average total order value for all orders on 2023-04-01."
    }
  ],
  temperature=0.0,
  max_tokens=64,
  top_p=1
)

print(response.choices[0].message.content)